name: Multi-Platform Build

on:
    workflow_dispatch:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: 01. Checkout code
      uses: actions/checkout@v4

    - name: 02. Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 03. Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 04. Build executable
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          pyinstaller --onefile --name myapp-${{ runner.os }}.exe src/main.py
        else
          pyinstaller --onefile --name myapp-${{ runner.os }} src/main.py
        fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ runner.os }}
        path: dist/
