name: Multi-Platform Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          pyinstaller --onefile --name myapp-${{ runner.os }}.exe src/app.py
        else
          pyinstaller --onefile --name myapp-${{ runner.os }} src/app.py
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ runner.os }}
        path: dist/
